[package]
name = "workflow-actions-functions"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
aws-sdk-s3.workspace = true
lambda_runtime.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
sha2.workspace = true
hex.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
application.workspace = true
pdf.workspace = true
domain.workspace = true
storage.workspace = true
time = { workspace = true, features = ["formatting", "macros"] }

[lints]
workspace = true
